ifndef TARGET
TARGET=z1
endif

DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
PROJECT_SOURCEFILES += cc2420.c

CONTIKI_PROJECT = sniffer

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
